added hello world in anang language
calixtocarolina/hello-world-all-langs pull request #45
Opened 2022-10-10 00:19 UTC by godswilludoh

2022-10-10 19:11 UTC, calixtocarolina requested changes
Please, add your info into the CONTRIBUTORS.md file following the convention in the README.md file so I can approve your PR.

2022-10-10 19:51 UTC, godswilludoh commented
Okay, I will do so immediately

On Mon, Oct 10, 2022 at 8:11 PM Carolina Calixto ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please, add your info into the CONTRIBUTORS.md file following the
> convention in the README.md file so I can approve your PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/calixtocarolina/hello-world-all-langs/pull/45#pullrequestreview-1136436685>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APZIPYCYRXTZTHMDVRYPORTWCRS5TANCNFSM6AAAAAARA472MQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-10-10 20:05 UTC, godswilludoh commented
Worked on changes requested.

2022-10-11 12:43 UTC, calixtocarolina approved these changes

2022-10-11 12:43 UTC, merged